/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrdersObjectPageObjectPage journey");

        opaTest("Navigate to SalesOrdersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheSalesOrdersListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheSalesOrdersListGenerated.onTable().iCheckRows();
            When.onTheSalesOrdersListGenerated.onTable().iPressRow(0);

            Then.onTheSalesOrdersObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSalesOrdersObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheSalesOrdersObjectPageGenerated.iPressSectionIconTabFilterButton("FieldGroup::General");
            Then.onTheSalesOrdersObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "ID" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "email" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "firstName" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "lastName" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "country" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "createOn" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "deliveryDate" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "orderStatus" });
            Then.onTheSalesOrdersObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "imageURL" });
            When.onTheSalesOrdersObjectPageGenerated.iPressSectionIconTabFilterButton("items::LineItem");
            Then.onTheSalesOrdersObjectPageGenerated.iCheckSection({ section: "items::LineItem" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});