/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrdersListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSalesOrdersListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheSalesOrdersListGenerated.onFilterBar().iCheckFilterField("ID");
            Then.onTheSalesOrdersListGenerated.onFilterBar().iCheckFilterField("email");
            Then.onTheSalesOrdersListGenerated.onFilterBar().iCheckFilterField("country");
            Then.onTheSalesOrdersListGenerated.onFilterBar().iCheckFilterField("orderStatus");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheSalesOrdersListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheSalesOrdersListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheSalesOrdersListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheSalesOrdersListGenerated.onTable().iCheckColumns(undefined, {"ID":{"header":"Sales Order ID"},"email":{"header":"Email"},"firstName":{"header":"First Name"},"lastName":{"header":"Last Name"},"country":{"header":"Country"},"createOn":{"header":"Created On"},"deliveryDate":{"header":"Delivery Date"},"orderStatus":{"header":"Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheSalesOrdersListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheSalesOrdersListGenerated.onTable().iCheckRows();

            When.onTheSalesOrdersListGenerated.onTable().iPressRow(0);
            Then.onTheSalesOrdersObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});